name: Yandex Cloud Functions deploy

on:
  workflow_run:
    workflows: [Pylint]
    types: [completed]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      python-version: "3.9"
      YC_SA_KEY: ${{secrets.YC_SA_KEY}}
      TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install Yandex Cloud SDK
        run: |
          python -m pip install --upgrade pip
          pip install yandexcloud
      - name: Run deployment script
        run: |
          python deploy_ycf.py
